name: CI/CD Pipeline for COSMOS Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GHCR_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build \
            --build-arg COSMOS_VERSION=4.5.2 \
            --tag ghcr.io/${{ github.actor }}/cosmos_delphy:latest \
            .

      - name: Save Docker Image Locally
        run: |
          mkdir -p /tmp/cosmos_delphy_cache
          docker save ghcr.io/${{ github.actor }}/cosmos_delphy:latest -o /tmp/cosmos_delphy_cache/cosmos_delphy.tar

      - name: Push Docker Image to GHCR
        run: |
          docker push ghcr.io/${{ github.actor }}/cosmos_delphy:latest

  test:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Pull Docker Image
        run: |
          docker pull ghcr.io/${{ github.actor }}/cosmos_delphy:latest

      - name: Run Tests in Container
        run: |
          docker run --rm \
            -e APP_HOME=/cosmos \
            ghcr.io/${{ github.actor }}/cosmos_delphy:latest \
            rspec --format documentation

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Pull Docker Image
        run: |
          docker pull ghcr.io/${{ github.actor }}/cosmos_delphy:latest

      - name: Deploy to Production
        run: |
          echo "Deploying COSMOS container to production environment"
          docker run -d --name cosmos_app \
            -e APP_HOME=/cosmos \
            ghcr.io/${{ github.actor }}/cosmos_delphy:latest
