# .github/workflows/ci.yml
# Modern CI/CD Pipeline for COSMOS with Testing and Deployment Stages

name: COSMOS CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker_build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Authenticate with GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u guygrubbs --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/guygrubbs/cosmos_delphy:latest .

      - name: Push Docker Image to GHCR
        run: |
          docker push ghcr.io/guygrubbs/cosmos_delphy:latest

      - name: Verify Docker Image
        run: |
          docker pull ghcr.io/guygrubbs/cosmos_delphy:latest
          docker run --rm ghcr.io/guygrubbs/cosmos_delphy:latest echo "Docker Image Successfully Built and Pushed"

  setup:
    name: Environment Setup
    runs-on: ubuntu-latest
    needs: docker_build
    container:
      image: ghcr.io/guygrubbs/cosmos_delphy:latest

    steps:
      - name: Validate Environment
        run: |
          ruby -v
          bundler -v
          rspec --version
          cmake --version
          qmake --version

      - name: Install Ruby Dependencies
        run: |
          bundle _1.17.3_ install --jobs=4 --retry=3

  lint:
    name: Code Linting
    runs-on: ubuntu-latest
    needs: setup
    container:
      image: ghcr.io/guygrubbs/cosmos_delphy:latest

    steps:
      - name: Run RuboCop
        run: bundle exec rubocop

  unit_tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: setup
    container:
      image: ghcr.io/guygrubbs/cosmos_delphy:latest

    steps:
      - name: Run Unit Tests
        run: bundle exec rspec tests/targets/DELPHY --format documentation

  integration_tests:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: setup
    container:
      image: ghcr.io/guygrubbs/cosmos_delphy:latest

    steps:
      - name: Run Integration Tests
        run: bundle exec rspec tests/targets/DELPHY/integration_test.rb --format documentation

  deployment:
    name: Deployment
    runs-on: ubuntu-latest
    needs: [lint, unit_tests, integration_tests]
    container:
      image: ghcr.io/guygrubbs/cosmos_delphy:latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Run Deployment Script
        run: |
          chmod +x deploy.sh
          ./deploy.sh

      - name: Validate Deployment Logs
        run: tail -n 50 /app/config/targets/DELPHY/tools/logs/*.log

  finalize:
    name: Finalization
    runs-on: ubuntu-latest
    needs: deployment

    steps:
      - name: Deployment Success
        run: echo "✅ Deployment Successful!"
