# CI/CD Pipeline for COSMOS v4 Deployment

name: COSMOS v4 CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  docker_build:
    name: Build and Push Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Authenticate with GitHub Container Registry
        run: echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io -u guygrubbs --password-stdin

      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/guygrubbs/cosmos_delphy:latest .

      - name: Push Docker Image to GHCR
        run: |
          docker push ghcr.io/guygrubbs/cosmos_delphy:latest

  setup:
    name: Environment Setup
    runs-on: ubuntu-latest
    needs: docker_build
    container:
      image: ghcr.io/guygrubbs/cosmos_delphy:latest

    steps:
      - name: Verify Tools
        run: |
          ruby -v
          bundler -v
          rake --version
          cmake --version
          qmake --version

      - name: Install Ruby Dependencies
        run: |
          bundle _1.17.3_ install --jobs=4 --retry=3

  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    needs: setup
    container:
      image: ghcr.io/guygrubbs/cosmos_delphy:latest

    steps:
      - name: Run Linter
        run: bundle exec rubocop

  unit_tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    needs: setup
    container:
      image: ghcr.io/guygrubbs/cosmos_delphy:latest

    steps:
      - name: Execute Unit Tests
        run: bundle exec rspec tests/targets/DELPHY --format documentation

  integration_tests:
    name: Run Integration Tests
    runs-on: ubuntu-latest
    needs: setup
    container:
      image: ghcr.io/guygrubbs/cosmos_delphy:latest

    steps:
      - name: Execute Integration Tests
        run: bundle exec rspec tests/targets/DELPHY/integration_test.rb --format documentation

  deployment:
    name: Deployment
    runs-on: ubuntu-latest
    needs: [lint, unit_tests, integration_tests]
    container:
      image: ghcr.io/guygrubbs/cosmos_delphy:latest

    steps:
      - name: Execute Deployment Script
        run: |
          chmod +x deploy.sh
          ./deploy.sh

      - name: Validate Logs
        run: tail -n 50 /cosmos/config/targets/DELPHY/tools/logs/*.log
