name: CI/CD Pipeline for COSMOS Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build \
            --build-arg COSMOS_VERSION=4.5.2 \
            --tag ghcr.io/${{ github.actor }}/cosmos_delphy:latest \
            .

      - name: Validate Docker Image Build
        run: |
          docker images | grep cosmos_delphy

      - name: Save Docker Image to Cache
        uses: actions/cache@v4
        with:
          path: /tmp/cosmos_delphy_cache
          key: docker-image-${{ github.sha }}

      - name: Save Docker Image
        run: |
          mkdir -p /tmp/cosmos_delphy_cache
          docker save ghcr.io/${{ github.actor }}/cosmos_delphy:latest -o /tmp/cosmos_delphy_cache/cosmos_delphy.tar

      - name: Push Docker Image to GHCR
        run: |
          docker push ghcr.io/${{ github.actor }}/cosmos_delphy:latest

  test:
    name: Run Tests in Docker Container
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Load Cached Docker Image
        uses: actions/cache@v4
        with:
          path: /tmp/cosmos_delphy_cache
          key: docker-image-${{ github.sha }}

      - name: Load Docker Image
        run: |
          docker load -i /tmp/cosmos_delphy_cache/cosmos_delphy.tar

      - name: Run COSMOS Launcher Validation
        run: |
          docker run --rm \
            -e COSMOS_VERSION=4.5.2 \
            -e APP_HOME=/cosmos \
            ghcr.io/${{ github.actor }}/cosmos_delphy:latest \
            ruby Launcher

      - name: Run Tests in Container
        run: |
          docker run --rm \
            -e APP_HOME=/cosmos \
            ghcr.io/${{ github.actor }}/cosmos_delphy:latest \
            rspec --format documentation

  lint:
    name: Run Code Linting
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Load Cached Docker Image
        uses: actions/cache@v4
        with:
          path: /tmp/cosmos_delphy_cache
          key: docker-image-${{ github.sha }}

      - name: Load Docker Image
        run: |
          docker load -i /tmp/cosmos_delphy_cache/cosmos_delphy.tar

      - name: Run Linter
        run: |
          docker run --rm \
            ghcr.io/${{ github.actor }}/cosmos_delphy:latest \
            rubocop

  deploy:
    name: Deploy to Production
    needs: [test, lint]
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Pull Docker Image
        run: |
          docker pull ghcr.io/${{ github.actor }}/cosmos_delphy:latest

      - name: Deploy to Production
        run: |
          echo "Deploying COSMOS container to production environment"
          docker run -d --name cosmos_app \
            -e COSMOS_VERSION=4.5.2 \
            -e APP_HOME=/cosmos \
            ghcr.io/${{ github.actor }}/cosmos_delphy:latest
