name: CI/CD Pipeline for COSMOS Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Authenticate with GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: 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

      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/guygrubbs/cosmos_delphy:latest .

      - name: Push Docker Image to GHCR
        run: |
          docker push ghcr.io/guygrubbs/cosmos_delphy:latest

      - name: Run Unit Tests
        run: |
          docker run --rm ghcr.io/guygrubbs/cosmos_delphy:latest rspec

      - name: Run Integration Tests
        run: |
          docker run --rm ghcr.io/guygrubbs/cosmos_delphy:latest bundle exec rake test

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Deploy to Production
        run: |
          echo "Deployment to production initiated"
          docker pull ghcr.io/guygrubbs/cosmos_delphy:latest
          docker run -d -p 2900:2900 ghcr.io/guygrubbs/cosmos_delphy:latest