name: CI/CD Pipeline for COSMOS Deployment

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build and Test Docker Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker Image
        run: |
          docker build -t ghcr.io/${{ github.actor }}/cosmos_delphy:latest .

      - name: Run Container Tests
        run: |
          docker run --rm \
            --name cosmos_test_container \
            -e DISPLAY=:99 \
            ghcr.io/${{ github.actor }}/cosmos_delphy:latest \
            ruby Launcher

      - name: Push Docker Image to GHCR
        if: github.ref == 'refs/heads/main'
        run: |
          docker push ghcr.io/${{ github.actor }}/cosmos_delphy:latest

  deploy:
    name: Deploy to Environment
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Pull Docker Image from GHCR
        run: |
          docker pull ghcr.io/${{ github.actor }}/cosmos_delphy:latest

      - name: Run Docker Container
        run: |
          docker run -d \
            --name cosmos_deploy_container \
            -e DISPLAY=:99 \
            -p 2900:2900 \
            -p 2901:2901 \
            -p 2902:2902 \
            ghcr.io/${{ github.actor }}/cosmos_delphy:latest

      - name: Verify Deployment
        run: |
          docker ps | grep cosmos_deploy_container
